"""
Stage 3 code generation -- and the ref0 reference impl used by Stage 2.

Each implementation is generated by an LLM call whose system prompt sees ONLY the
spec, never any battery and never another implementation. This is anti-circularity
rule 1 enforced structurally: the test-author context (synth/generate.py), the
implementer context (here), and the mutant-author context (mutate.py) are separate
API calls with separate system prompts and no shared conversation.

  generate_impl(spec, candidate_id, temperature, seed)  -> (Candidate, usage)
  generate_ref0(spec)                                    -> the Stage-2 reference impl
  generate_impls(spec, n)                                -> N independent Stage-3 impls
"""
import re

from . import records, keys


_IMPL_SYSTEM = """You are a ComfyUI custom-node implementer. Given a specification \
(a plain-language description + input/output contract + confirmed examples and \
invariants), write a COMPLETE, CORRECT implementation as a single ComfyUI node class.

ComfyUI conventions:
- IMAGE tensor: torch.float32, shape [B, H, W, C], values in [0,1], C=3 (RGB).
- MASK tensor: torch.float32, shape [B, H, W], values in [0,1] (NO channel dimension).
- A node is a class with: a classmethod INPUT_TYPES() returning the required/optional
  dict; RETURN_TYPES (a tuple of type strings); optional RETURN_NAMES; FUNCTION (the
  method name, as a string); CATEGORY (a string); and the method named by FUNCTION,
  which returns a tuple matching RETURN_TYPES.
- The method signature must accept the inputs by the names declared in INPUT_TYPES.

Requirements:
- Implement EXACTLY what the spec says. Honor every confirmed example and invariant.
- Respect the declared INPUT_TYPES and RETURN_TYPES precisely (shapes, ranges, dtypes,
  the MASK [B,H,W] vs IMAGE [B,H,W,C] convention).
- Be deterministic. No randomness, no network, no file I/O, no global state.
- Operate on the whole batch. Clamp outputs to [0,1] when the contract says so.

Output ONLY a Python module: imports (torch etc.) + the single node class. No markdown
fences, no prose, no explanation."""


def _strip_fences(text):
    text = text.strip()
    m = re.search(r"```(?:python)?\s*\n(.*?)```", text, re.DOTALL)
    return m.group(1).strip() if m else text


def _first_node_class_name(source):
    names = re.findall(r"^class\s+([A-Za-z_]\w*)", source, re.MULTILINE)
    return names[0] if names else "Node"


def generate_impl(spec, candidate_id, temperature=0.7, seed=0,
                  model="claude-sonnet-4-6", client=None):
    """Generate one node implementation from the spec. Returns (Candidate, usage)."""
    client = client or keys.anthropic_client()
    spec_text = spec.to_spec_string()
    user = (f"SPECIFICATION (variant {seed}):\n\n{spec_text}\n\n"
            "Write the implementation now. Output only the Python module.")
    resp = client.messages.create(
        model=model, max_tokens=2000, temperature=temperature,
        system=[{"type": "text", "text": _IMPL_SYSTEM,
                 "cache_control": {"type": "ephemeral"}}],
        messages=[{"role": "user", "content": user}],
    )
    src = _strip_fences("".join(b.text for b in resp.content if b.type == "text"))
    cname = _first_node_class_name(src)
    return records.Candidate(id=candidate_id, source=src, class_name=cname,
                             origin="ref0" if candidate_id == "ref0" else "impl",
                             temperature=temperature), resp.usage


def generate_ref0(spec, model="claude-sonnet-4-6", client=None):
    """The Stage-2 reference impl: one draw at moderate temperature."""
    return generate_impl(spec, "ref0", temperature=0.4, seed=999, model=model, client=client)


def generate_impls(spec, n=3, model="claude-sonnet-4-6", client=None):
    """N independent Stage-3 implementations, varied temperature. Returns
    ([Candidate], [usage])."""
    client = client or keys.anthropic_client()
    temps = [0.3, 0.7, 1.0, 0.5, 0.9, 0.2]
    cands, usages = [], []
    for i in range(n):
        c, u = generate_impl(spec, f"impl_{i}", temperature=temps[i % len(temps)],
                             seed=i, model=model, client=client)
        cands.append(c)
        usages.append(u)
    return cands, usages
